### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by djbadders**
Fixed some issues with exception handling that could cause PTM to become unresponsive

### CODE REVIEW

**Comment by HojouFotytu** [comment]
Coinbase?  Did you mean Binance?

**Comment by djbadders** [comment]
It was losing the thread whilst calling CoinMarketCap which I tracked down to exceptions in the exception handler which caused the thread to terminate and leave PTM hung

**Comment by djbadders** [comment]
Log trace:

8|ptm btc2 | 2019/09/07 01:16:34.041 INFO -
8|ptm btc2 | 2019/09/07 01:16:34.041 INFO - Cleaned up logfiles.
8|ptm btc2 | 2019-09-07 01:21 +02:00: 2019/09/07 01:21:25.257 INFO -
8|ptm btc2 | 2019/09/07 01:21:25.257 INFO - ##########################################################
8|ptm btc2 | 2019/09/07 01:21:25.257 INFO - #********************************************************#
8|ptm btc2 | 2019/09/07 01:21:25.257 INFO - Starting market trend check with Version 2.2.7
8|ptm btc2 | 2019/09/07 01:21:25.257 INFO - Loading current Profit Trailer properties from preset files...
8|ptm btc2 | 2019-09-07 01:21 +02:00: 2019/09/07 01:21:25.272 INFO - Properties loaded - P (122 lines) - D (96 lines) - I (70 lines).
8|ptm btc2 | 2019/09/07 01:21:25.272 INFO - Loading Single Market Setting Summaries...
8|ptm btc2 | 2019/09/07 01:21:25.274 INFO - Single Market Setting Summaries loaded.
8|ptm btc2 | 2019-09-07 01:21 +02:00: 2019/09/07 01:21:25.277 INFO - CoinMarketCap - Getting market data...
8|ptm btc2 | 2019-09-07 01:26 +02:00: 2019/09/07 01:26:25.267 WARN - PTMagic has been raiding since 9/7/19 1:21:25 AM.  Checking things...
8|ptm btc2 | 2019-09-07 01:31 +02:00: 2019/09/07 01:31:25.282 WARN - PTMagic has been raiding since 9/7/19 1:21:25 AM.  Checking things...
8|ptm btc2 | 2019/09/07 01:31:25.282 WARN - PTMagic raid 7 is taking longer than expected.  Consider increasing your IntervalMinues setting, reducing other processes on your PC, or raising PTMagic's priority.
8|ptm btc2 | 2019/09/07 01:31:25.282 INFO - PTMagic status reset, waiting for the next raid to be good to go again.

**Comment by djbadders** [comment]
Yup should have read coinmarketcap

**Pull request merged**
