### PR TITLE
Pairs and DCA, Bag Analyser enhanced to highlight pairs with no value in red

### PR DESCRIPTION
**Pull request by djbadders**
Pairs and DCA, Bag Analyser enhanced to highlight pairs with no value in red. This is to help users notice when PT loses prices which it does occasionally.

### CODE REVIEW

**Comment by JackTerok** [comment]
Could you provide a screenshot on how this looks?

**Comment by djbadders** [comment]
image

Same style on the Bag Analyser

**Comment by djbadders** [comment]
Updated to move the No Value message to the percentage column and also set the warning if the average bought price is 0.0

**Comment by HojouFotytu** [comment]
Looks good.   Nice work.

As we discussed in chat, the conflicts and previous commits are a problem.

Resubmitted as a clean PR https://github.com/PTMagicians/PTMagic/pull/78

**Pull request closed without merging**
