### PR TITLE
Fix for issue #90 stops SMS settings getting stuck

### PR DESCRIPTION
**Pull request by djbadders**
This is a significant change as PTM now always regenerates the PT settings using the preset files and not by loading settings lines from PT. This change however simplifies the code and resolves issue #90 which is a significant issue.

### CODE REVIEW

**Comment by HojouFotytu** [comment]
Having a hard time isolating how it works in the code... but the runtime summary now shows:

2019/03/14 22:08:01.291 INFO - + Global setting changed: Yes

after every run, even when there was no change.

**Comment by djbadders** [comment]
@HojouFotytu If you changed you analyser settings this forces an update skipping the flood protection check, so unfortunately this isn't a valid test method for flood protection. You need the global market to change more than once in the 20 mins, or set the flood protection to long and ensure it stops the change.

I have been unable to replicate the issue you reported with the summary reporting global setting changes when there hasn't been a change. I haven't changed the logic around how this is calculated.

**Comment by HojouFotytu** [comment]
@djbadders 

Yeah, that makes sense that a enforced update would ignore flood protection, as it should.  And after playing with it a bit more, that's the reason it is falsely reporting a change to the global settings -- any update to the settings meets the condition to report the global setting changed.

I'm considering removing that line completely, since it is misleading for the summary to show that global settings were changed, when in fact they weren't.   And do we really need to know that the setting changed or not, when it shows the current setting on the line right above it?  

The problem is, that same line conditionally displays when flood protection prevents a change.

So how about this?  We remove that line completely, but if flood protection is on, we show something like "Flood protection acitve: x minutes remaining"

What do you think?

**Comment by HojouFotytu** [comment]
There is already another instance in the telegram code which does this, we can simply duplicate this line for the runtime summary:

image

**Comment by HojouFotytu** [comment]
Poking around, there is already another instance in the telegram code which does what i suggested above, we can simply duplicate this line for the runtime summary:

image

**Comment by HojouFotytu** [comment]
I'm also seeing this on every run, even if I don't touch the files:

2019/03/15 13:15:54.641 INFO - Preset files changed, enforcing preparation check...
...
2019/03/15 13:16:03.450 INFO - Applying 'SidewaysUP' as the settings.analyzer.json or a preset file got changed.
....
2019/03/15 13:16:59.341 INFO - + Files changed: Yes

According to the logic, a change to the header timestamp is what counts as a files changed -- but the header will be changed every run since your change to the SMS logic will cause a change every run.

**Comment by HojouFotytu** [comment]
I made another small change to the raid summary -- "PT config changed"  rather than "Files Changed" for clarity.

**Pull request merged**
