### PR TITLE
Performance improvements using parallelism

### PR DESCRIPTION
**Pull request by djbadders**
Improved the performance of creating the PT data sets for polling and significantly improved getting market ticks process using parallelism.

### CODE REVIEW

**Comment by HojouFotytu** [comment]
gonna defer to @JackTerok on this.  ;)

**Comment by djbadders** [comment]
Refreshed 24hrs worth of ticks which is the maximum amount I believe, and worked fine. I had similar worries but seems ok. Can you please do the same test, as I would like to be certain. I set the degree of parallelism to 5 threads to limit the amount of concurrent calls to binance.

**Comment by djbadders** [comment]
@nnation I can only test Binance but in principle the same change will work on other exchanges. Do you have test accounts on other exchanges?

**Comment by HojouFotytu** [comment]
> Refreshed 24hrs worth of ticks which is the maximum amount I believe, and worked fine. I had similar worries but seems ok. Can you please do the same test, as I would like to be certain. I set the degree of parallelism to 5 threads to limit the amount of concurrent calls to binance.

I use 30days of data.

**Comment by djbadders** [comment]
> Did you test this with a fresh installation so that PTM gets all fresh data? I'm asking because sometimes if you make calls to binance too quickly they block you for a few minutes.

Ok tested several times from new with 30 day trend on the graph and no issues on Binance, so all good.

**Comment by djbadders** [comment]
> > Refreshed 24hrs worth of ticks which is the maximum amount I believe, and worked fine. I had similar worries but seems ok. Can you please do the same test, as I would like to be certain. I set the degree of parallelism to 5 threads to limit the amount of concurrent calls to binance.
> 
> I use 30days of data. and yeah, i didn't consider other exchanges.
> 
> I think we need to test this for sure. Probably not a bad idea to go ahead and merge it, and then create a beta release -- hopefully we can find a few people to test it on other exchanges.

I have retested using a 30 day average and all was fine on Binance.

**Comment by djbadders** [comment]
The Poloniex and Bittrex exchange market analysers have been updated with the same change, but I cannot test them directly as I don't have accounts. Do any of you guys have accounts and could test?

**Pull request merged**
