### PR TITLE
Charts update

### PR DESCRIPTION
**Pull request by HojouFotytu**
- added "Daily" to chart Y axis for clarity
- added a new "Asset Distribution" chart to the dashboard
- ~~moved "sales overview" to column bottom~~
- ~~reduced daily profits chart on dashboard from 30 days to 10 days~~
- ~~resized dashboard trend chart to line up with the bottom of "sales overview"~~

### CODE REVIEW

**Comment by djbadders** [comment]
Can you add a screen shot please. Also reducing the sales overview from 30 to 10 days isn't a change I would want, and I suspect many more; being able to quickly see the rolling month performance is very handy. I recommend you make it a configurable parameter if you want to change it on your instances.

**Comment by HojouFotytu** [comment]
The reason I reduced the sales to 10 days wasn’t just for me, but because I was thinking the dashboard didn’t need to show so much history — that’s what the sales analyzer page is for.   But now that you mention it, you are probably right.   After all, the sales overview also shows 30 days so they should probably be consistent.

**Comment by HojouFotytu** [comment]
I posted a screenshot for discussion on our discord.

**Comment by HojouFotytu** [comment]
Rearranged the layout a bit, and reverted the change to the daily profit chart.

**Pull request merged**
